<?php

namespace AppBundle\Repository;

/**
 * HistoryNotepadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryNotepadRepository extends \Doctrine\ORM\EntityRepository
{
}
