<?php

namespace AppBundle\Repository;

/**
 * RodNagiosProblemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RodNagiosProblemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlarms(){

    }

}
