<?php

namespace AppBundle\Entity\ROD;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryTicketRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class HistoryTicketRepository extends EntityRepository
{



}
