<?php

namespace AppBundle\Repository\PlugSla;

/**
 * GroupeTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
