<?php

namespace AppBundle\Repository\PlugSla;

/**
 * InternalCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternalCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
