<?php

namespace AppBundle\Repository\PlugSla;

/**
 * SOProvideurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SOProvideurRepository extends \Doctrine\ORM\EntityRepository
{
}
