<?php

namespace AppBundle\Repository\PlugSla;

/**
 * TypeTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
