<?php

namespace AppBundle\Repository\ROD;

/**
 * TicketAlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAlarmRepository extends \Doctrine\ORM\EntityRepository
{
}
